return {
  -- 'olimorris/codecompanion.nvim',
  -- dependencies = {
  --   'nvim-lua/plenary.nvim',
  --   'nvim-treesitter/nvim-treesitter',
  --   'hrsh7th/nvim-cmp', -- Optional: For using slash commands and variables in the chat buffer
  --   'nvim-telescope/telescope.nvim', -- Optional: For using slash commands
  --   { 'stevearc/dressing.nvim', opts = {} }, -- Optional: Improves `vim.ui.select`
  -- },
  -- config = function()
  --   require('codecompanion').setup {
  --     display = {
  --       diff = {
  --         provider = 'telescope',
  --       },
  --     },
  --     strategies = {
  --       chat = {
  --         adapter = 'gemini',
  --       },
  --       inline = {
  --         adapter = 'gemini',
  --       },
  --     },
  --     adapters = {
  --       gemini = function()
  --         return require('codecompanion.adapters').extend('gemini', {
  --           env = {
  --             api_key = os.getenv("GEMINI_KEY")
  --           },
  --         })
  --       end,
  --     },
  --   }
  -- end,
}
