return {
    filetypes = {
        "html",
        "css",
        "javascriptreact",
        "typescriptreact",
        "scss",
        "haml",
        "xml",
        "xsl",
        "pug",
        "slim",
        "sass",
        "stylus",
        "less",
        "sss",
        "hbs",
        "handlebars",
    },
}
