format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$nix_shell\
$golang\
$nodejs\
$rust\
$elixir\
$ocaml\
$cmd_duration $jobs $time\
$line_break\
$character"""

[gcloud]
disabled = false

[aws]
disabled = true

[directory]
style = 'bold bright-cyan'

[nix_shell]
symbol = '❄️'
impure_msg = ''
