#!/usr/bin/env node

const timestamp = Number(process.argv[2]);

if (Number.isNaN(timestamp)) {
  console.error("Usage: cts <timestamp>");
  process.exit(1);
}

const date = new Date(timestamp);

console.log("Local:", date.toString());
console.log("UTC:  ", date.toISOString());
