#!/bin/bash

if [[ -f package-lock.json ]]; then
  echo 'npm aqui'
  npm run dev
  exit 0
fi

if [[ -f yarn.lock ]]; then
  echo 'yarn aqui'
  yarn dev
  exit 0
fi

if [[ -f pnpm-lock.yaml ]]; then
  echo 'pnpm aqui'
  pnpm run dev
  exit 0
fi

echo "not a node project"
