#!/bin/bash

SECRET_ID="$1"
OS=$(uname)

if [[ $OS == "Darwin" ]]; then
  sed -i '' '/^AWS_ACCESS_KEY_ID/d; /^AWS_SECRET_ACCESS_KEY/d' .env
  rm -f .envrc.custom
  direnv reload

  aws secretsmanager get-secret-value --secret-id "$SECRET_ID" --query SecretString --output text |
    jq -r 'to_entries | map("\(.key)=\(.value|tostring)") | .[]' >> .envrc.custom
elif [[ $OS == "Linux" ]]; then
  sed -i '/^AWS_ACCESS_KEY_ID/d;/^AWS_SECRET_ACCESS_KEY/d' .env
  rm -f .envrc.custom
  direnv reload

  aws secretsmanager get-secret-value --secret-id "$secret_id" --query SecretString --output text |
    jq -r 'to_entries | map("\(.key)=\"\(.value|tostring)\"") | .[]' >> .envrc.custom
fi


echo 'AWS_ACCESS_KEY_ID="<secret>"' >> .env
echo 'AWS_SECRET_ACCESS_KEY="<secret>"' >> .env

direnv reload
