#!/bin/bash

if [[ $OSTYPE == "darwin"* ]]; then
  brew install gum
elif [[ $OSTYPE == "linux-gnu"* ]]; then
  DISTRO=$(cat /etc/os-release | grep "^ID=" | grep -o "=.*" | grep -o "\w\+")
  case $DISTRO in
    ubuntu|debian|pop|linuxmint)
      sudo mkdir -p /etc/apt/keyrings
      curl -fsSL https://repo.charm.sh/apt/gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/charm.gpg
      echo "deb [signed-by=/etc/apt/keyrings/charm.gpg] https://repo.charm.sh/apt/ * *" | sudo tee /etc/apt/sources.list.d/charm.list
      sudo apt update && sudo apt install gum
      ;;
    arch|manjaro-arch)
      sudo pacman -S gum
      ;;
    fedora)
      echo '[charm]
      name=Charm
      baseurl=https://repo.charm.sh/yum/
      enabled=1
      gpgcheck=1
      gpgkey=https://repo.charm.sh/yum/gpg.key' | sudo tee /etc/yum.repos.d/charm.repo
      sudo yum install gum
      ;;
  esac
fi
