#!/bin/bash

set -eo pipefail
if test -n "$SSH_TTY"; then
  nc -q1 localhost 2224
elif test "$(uname)" = Darwin; then
  /usr/bin/pbcopy
elif test "$(echo $XDG_SESSION_TYPE)" = wayland; then
  wl-copy
else
  xsel --clipboard --input
fi
