#!/bin/bash

temp="/tmp/ticethingy"
vars="/tmp/ticevars"

if [[ ! -f $vars ]]; then 
  printf "40\n0" > $vars
fi

timer() {
  [[ -f $temp ]] && stop
  echo "" > $temp
  while true
  do
    if [[ $(( SECOND / 10 )) -lt 1 ]]; then
      echo "🧿  $MINUTE:0$SECOND" >> $temp
    else
      echo "🧿  $MINUTE:$SECOND" >> $temp
    fi
    sleep 0.99078
    SECOND=$(( $SECOND - 1 ))
    if [[ $MINUTE -gt 0 && $SECOND -lt 0 ]]; then
      MINUTE=$(( $MINUTE - 1 ))
      SECOND=59
    fi

    [[ $MINUTE -eq 0 && $SECOND -lt 0 ]] && break
  done
  rm $temp
}

start() {
  if [[ "$1" == "hour" ]]; then
    MINUTE=$(( 59 - $(date +"%M" | sed 's/^[0]*//')))
    SECOND=$(( 60 - $(date +"%S" | sed 's/^[0]*//')))
  elif [[ -z "$1" ]]; then
    MINUTE=$(head -1 $vars)
    SECOND=$(head -2 $vars | tail -1)
  else
    MINUTEINPUT=$(echo $1 | grep -o '[0-9]\+[mM]' | grep -o '[0-9]*')
    SECONDINPUT=$(echo $1 | grep -o '[0-9]\+[sS]' | grep -o '[0-9]*')
    MINUTE=0
    SECOND=0

    if [ ! -z "$MINUTEINPUT" ]; then
      for min in ${MINUTEINPUT[@]}
      do
        MINUTE=$(( $MINUTE + $min ))
      done
    fi

    if [ ! -z "$SECONDINPUT" ]; then
      for min in ${SECONDINPUT[@]}
      do
        SECOND=$(( $SECOND + $min ))
      done
    fi
  fi

  if [[ $SECOND -ge 60 ]]; then
    MINUTE=$(( $MINUTE + $(( $SECOND / 60 ))))
    SECOND=$(( $SECOND % 60 ))
  fi

  timer & 
  sleep 0.3
  sed -i '' "1s/^/$!\n/" $temp
}

set() {
  MINUTEINPUT=$(echo $1 | grep -o '[0-9]\+[mM]' | grep -o '[0-9]*')
  SECONDINPUT=$(echo $1 | grep -o '[0-9]\+[sS]' | grep -o '[0-9]*')
  MINUTE=0
  SECOND=0
  if [ ! -z "$MINUTEINPUT" ]; then
    for min in ${MINUTEINPUT[@]}
    do
      MINUTE=$(( $MINUTE + $min ))
    done
  fi
  if [ ! -z "$SECONDINPUT" ]; then
    for min in ${SECONDINPUT[@]}
    do
      SECOND=$(( $SECOND + $min ))
    done
  fi
  if [[ $SECOND -ge 60 ]]; then
    MINUTE=$(( $MINUTE + $(( $SECOND / 60 ))))
    SECOND=$(( $SECOND % 60 ))
  fi
  printf "$MINUTE\n$SECOND" > $vars
}

stop() {
  MYSELF=$(head -n 1 $temp)
  kill $MYSELF
  sleep 0.1
  rm $temp
}

var() {
  MINUTE=$(head -1 $vars)
  SECOND=$(tail -1 $vars)
  echo "${MINUTE}m ${SECOND}s"
}

show() {
  if [[ -f $temp ]];then
    echo $(tail -n 1 $temp)
  else
    echo ""
  fi
}

[[ -z "$@" ]] && show || "$@"

# Completion stuff
if [[ -n $COMP_LINE ]]; then
  printf "start\nstop\nshow\nset\nvar"
  exit
fi
