#!/bin/bash

while IFS= read -r line
do
    if [[ -n $line ]]; then
      line=$(echo "$line" | xargs)
      setLine=$(echo "$line" | gsed "s/./\U&/")
      printf "const [%s, set%s] = useState()" "$line" "$setLine"
    fi
done
