#!/bin/bash

ZET_FOLDER="$HOME/Documents/zet"
QUICK_FOLDER="$ZET_FOLDER/quick"

if [ ! -d "$ZET_FOLDER" ]; then
  mkdir $ZET_FOLDER
fi

zet() {
  FILENAME=$(echo $@ | tr " " "_").md
  FILEPATH=$ZET_FOLDER/$FILENAME

  if [[ -f "$FILEPATH" ]] ; then
    read -p "$FILENAME already exists. Edit? " yes
    case "$yes" in
      y|yes|s|sim|ok|dale) nvim "$FILEPATH"
    esac
    exit 0
  fi

  echo "### $(now)" >> $FILEPATH
  nvim $FILEPATH
}

quik() {
  FILENAME=$(echo $@ | tr " " "_").md
  FILEPATH=$QUICK_FOLDER/$FILENAME

  if [[ -f "$FILEPATH" ]] ; then
    read -p "$FILENAME already exists. Edit? " yes
    case "$yes" in
      y|yes|s|sim|ok|dale) nvim "$FILEPATH"
    esac
    exit 0
  fi

  # touch $FILEPATH
  echo "### $(now)" >> $FILEPATH
  nvim $FILEPATH
}

get() {
  NOTE=$(ls -F $ZET_FOLDER | grep -v "/$" | fzf) && nvim "$ZET_FOLDER/$NOTE"
}

"$@"

# Completion stuff
if [[ -n $COMP_LINE ]]; then
  printf "zet\nquik\nget\n"
  exit
fi
