-- local M = {
--   base46 = {
--     theme = 'onedark',
--   },
--
--   ui = {
--     telescope = { style = 'borderless' },
--     statusline = { enabled = false },
--     tabufline = { enabled = false },
--   },
-- }
--
-- return M
