vim.cmd("hi clear")
vim.cmd("syntax reset")
vim.cmd("let g:colors_name = 'theBenjamin'")
vim.cmd("set background=dark")
vim.cmd("set t_Co=256")
vim.cmd("hi Normal guifg=#none ctermbg=NONE guibg=none gui=NONE")

vim.cmd("hi DiffText guifg=#f0eded guibg=NO")
vim.cmd("hi ErrorMsg guifg=#f0eded guibg=NONE")
vim.cmd("hi WarningMsg guifg=#f0eded guibg=NONE")
vim.cmd("hi PreProc guifg=#f0eded guibg=NONE")
vim.cmd("hi Exception guifg=#f0eded guibg=NONE")
vim.cmd("hi Error guifg=#f0eded guibg=NONE")
vim.cmd("hi DiffDelete guifg=#f0eded guibg=NONE")
vim.cmd("hi GitGutterDelete guifg=#f0eded guibg=NONE")
vim.cmd("hi GitGutterChangeDelete guifg=#f0eded guibg=NONE")
vim.cmd("hi cssIdentifier guifg=#f0eded guibg=NONE")
vim.cmd("hi cssImportant guifg=#f0eded guibg=NONE")
vim.cmd("hi Type guifg=#f0eded guibg=NONE")
vim.cmd("hi Identifier guifg=#f0eded guibg=NONE")
vim.cmd("hi PMenuSel guifg=#ffdd33 guibg=NONE")
vim.cmd("hi Constant guifg=#ffdd33 guibg=NONE")
vim.cmd("hi Repeat guifg=#ffdd33 guibg=NONE")
vim.cmd("hi DiffAdd guifg=#ffdd33 guibg=NONE")
vim.cmd("hi GitGutterAdd guifg=#ffdd33 guibg=NONE")
vim.cmd("hi cssIncludeKeyword guifg=#ffdd33 guibg=NONE")
vim.cmd("hi Keyword guifg=#ffdd33 guibg=NONE")
vim.cmd("hi IncSearch guifg=#adadab guibg=NONE")
vim.cmd("hi Title guifg=#adadab guibg=NONE")
vim.cmd("hi PreCondit guifg=#adadab guibg=NONE")
vim.cmd("hi Debug guifg=#adadab guibg=NONE")
vim.cmd("hi SpecialChar guifg=#adadab guibg=NONE")
vim.cmd("hi Conditional guifg=#adadab guibg=NONE")
vim.cmd("hi Todo guifg=#adadab guibg=NONE")
vim.cmd("hi Special guifg=#adadab guibg=NONE")
vim.cmd("hi Label guifg=#adadab guibg=NONE")
vim.cmd("hi Delimiter guifg=#adadab guibg=NONE")
vim.cmd("hi Number guifg=#adadab guibg=NONE")
vim.cmd("hi CursorLineNR guifg=#adadab guibg=NONE")
vim.cmd("hi Define guifg=#adadab guibg=NONE")
vim.cmd("hi MoreMsg guifg=#adadab guibg=NONE")
vim.cmd("hi Tag guifg=#adadab guibg=NONE")
vim.cmd("hi String guifg=#73c936 guibg=NONE")
vim.cmd("hi MatchParen guifg=#adadab guibg=NONE")
vim.cmd("hi Macro guifg=#adadab guibg=NONE")
vim.cmd("hi DiffChange guifg=#adadab guibg=NONE")
vim.cmd("hi GitGutterChange guifg=#adadab guibg=NONE")
vim.cmd("hi cssColor guifg=#adadab guibg=NONE")
vim.cmd("hi Function guifg=#ffffff guibg=NONE")
vim.cmd("hi Directory guifg=#ffdd33 guibg=NONE")
vim.cmd("hi markdownLinkText guifg=#ffdd33 guibg=NONE")
vim.cmd("hi javaScriptBoolean guifg=#ffdd33 guibg=NONE")
vim.cmd("hi Include guifg=#ffdd33 guibg=NONE")
vim.cmd("hi Storage guifg=#ffdd33 guibg=NONE")
vim.cmd("hi cssClassName guifg=#ffdd33 guibg=NONE")
vim.cmd("hi cssClassNameDot guifg=#ffdd33 guibg=NONE")
vim.cmd("hi Statement guifg=#f0eded guibg=NONE")
vim.cmd("hi Operator guifg=#f0eded guibg=NONE")
vim.cmd("hi cssAttr guifg=#f0eded guibg=NONE")
vim.cmd("hi NormalFloat guifg=NONE guibg=none guisp=NONE gui=NONE cterm=NONE")

-- Nvimtree
vim.cmd("highlight NvimTreeCursorLine guifg=NONE guibg=#18252D guisp=NONE gui=NONE cterm=NONE")
vim.cmd("highlight! link NvimTreeCursorColumn NvimTreeCursorLine")
vim.cmd("highlight NvimTreeNormal guifg=#C6D5CF guibg=none guisp=NONE gui=NONE cterm=NONE")
vim.cmd("highlight NvimTreeRootFolder guifg=#8190D4 guibg=NONE guisp=NONE gui=bold cterm=bold")
vim.cmd("highlight NvimTreeSpecialFile guifg=#B279A7 guibg=NONE guisp=NONE gui=underline cterm=underline")
vim.cmd("highlight NvimTreeSymlink guifg=#8190D4 guibg=NONE guisp=NONE gui=NONE cterm=NONE")
vim.cmd("highlight NvimTreeWinSeparator guifg=bg guibg=NONE guisp=NONE gui=NONE cterm=NONE")

vim.cmd("hi Pmenu guifg=#e4e4ef guibg=#454545")
vim.cmd("hi SignColumn guibg=none")
vim.cmd("hi Title guifg=#e4e4ef")
vim.cmd("hi LineNr guifg=#41a7fc guibg=none")
vim.cmd("hi NonText guifg=#0f191f guibg=none")
vim.cmd("hi Comment guifg=#8A898A gui=italic")
vim.cmd("hi SpecialComment guifg=#b89140 gui=italic guibg=NONE")
vim.cmd("hi CursorLine guibg=#454545")
vim.cmd("hi TabLineFill gui=NONE guibg=#454545")
vim.cmd("hi TabLine guifg=#6464a3 guibg=#454545 gui=NONE")
vim.cmd("hi StatusLine gui=bold guibg=#454545 guifg=#e4e4ef")
vim.cmd("hi StatusLineNC gui=NONE guibg=#181818 guifg=#e4e4ef")
vim.cmd("hi Search guibg=#b89140 guifg=#e4e4ef")
vim.cmd("hi VertSplit gui=NONE guifg=#454545 guibg=NONE")
vim.cmd("hi Visual gui=NONE guibg=#454545")
