# vim:ft=kitty

## name: Árvore Dark
## license: MIT
## author: Árvore Theme
## upstream: https://github.com/arvore-theme

background #151E23
foreground #E6FAF7
selection_background #1C4D47
selection_foreground #E6FAF7
url_color #66DCCE
cursor #40CAB6
cursor_text_color #151E23

# Tabs
active_tab_background #40CAB6
active_tab_foreground #151E23
inactive_tab_background #121D24
inactive_tab_foreground #7C98A1

# Windows
active_border_color #40CAB6
inactive_border_color #2A3A42

# normal
color0 #151E23
color1 #FA5371
color2 #4EC685
color3 #FDD351
color4 #6394F3
color5 #9272DC
color6 #66DCCE
color7 #E6FAF7

# bright
color8  #7C98A1
color9  #FC98AB
color10 #B3E577
color11 #FEE596
color12 #8DAEF6
color13 #B29CE7
color14 #8DE5DA
color15 #F9FCFF

# extended colors
color16 #FCA78D
color17 #FA163E
